package in.ac.iitm.guide;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.stream.Collectors;
import java.util.stream.StreamSupport;
import org.junit.jupiter.api.Test;
import org.springframework.modulith.core.ApplicationModule;
import org.springframework.modulith.core.ApplicationModules;
import org.springframework.modulith.docs.Documenter;
import org.springframework.util.FileSystemUtils;

/**
 * Guards the slice boundaries described in docs/ai/architecture-rules.md.
 *
 * <p>A slice may only be reached through the types that sit directly in its own package; anything
 * in a nested package is internal to that slice. This test fails the build when one slice reaches
 * into another one's internals, which is the failure mode that matters when two people work on
 * different slices at the same time.
 */
class ModularityTest {

    /** Gitignored with the rest of {@code target/}: regenerated by every build, so it cannot go stale. */
    private static final String CANVAS_FOLDER = "target/spring-modulith-docs";

    /** How Modulith names a module in the PlantUML it writes: the application, twice, then the slice. */
    private static final String NODE = "GuideApplication.GuideApplication.";

    private static final ApplicationModules MODULES = ApplicationModules.of(GuideApplication.class);

    /**
     * The ten slices of docs/ai/architecture-rules.md, plus {@code shared}.
     *
     * <p>Kept as a literal list rather than derived from the packages, because deriving it would
     * make the assertion agree with whatever the code happens to contain — including agreeing that
     * there is nothing at all.
     */
    private static final String[] DOCUMENTED_MODULES = {
        "home", "articleview", "search", "taxonomy", "contribute",
        "moderate", "report", "media", "wikilink", "backup",
        "shared",
    };

    @Test
    void slices_do_not_reach_into_each_others_internals() {
        MODULES.verify();
    }

    /**
     * Without this, the test above passes on an application that has no slices at all: {@code
     * verify()} finds no boundary to violate and reports success. That was true of this repository
     * until 10 September, when the ten modules were declared — the test was green the whole time and
     * proved nothing. An empty pass and a real pass have to be distinguishable.
     */
    @Test
    void every_slice_in_the_architecture_map_is_a_module() {
        var detected = StreamSupport.stream(MODULES.spliterator(), false)
                .map(ApplicationModule::getName)
                .collect(Collectors.toSet());

        assertThat(detected).containsExactlyInAnyOrder(DOCUMENTED_MODULES);
    }

    /**
     * The canvas is the architecture as the code has it, not as a diagram someone drew. Reading the
     * files back, rather than trusting {@code writeModuleCanvases()} not to throw, is what stops
     * this passing on an empty output folder; deleting the folder first is what stops it passing on
     * the files of a previous build when the writer no longer runs.
     */
    @Test
    void the_build_writes_a_canvas_for_every_slice() throws IOException {
        FileSystemUtils.deleteRecursively(Path.of(CANVAS_FOLDER));

        new Documenter(MODULES, Documenter.Options.defaults().withOutputFolder(CANVAS_FOLDER)).writeModuleCanvases();

        for (var module : DOCUMENTED_MODULES) {
            var canvas = Path.of(CANVAS_FOLDER, "module-" + module + ".adoc");

            assertThat(canvas).as("canvas of %s", module).isRegularFile();
            assertThat(Files.readString(canvas)).as("canvas of %s", module).contains(module);
        }
    }

    /**
     * The component diagram as the code draws it, not as someone designed it: the arrows are the
     * imports between slices that exist now. {@code home}, {@code articleview} and {@code backup}
     * each use a published type of {@code wikilink}, so those three arrows have to be in it. The
     * folder is emptied first for the same reason as in the canvas test.
     */
    @Test
    void the_build_draws_the_dependencies_between_slices_that_the_code_has() throws IOException {
        FileSystemUtils.deleteRecursively(Path.of(CANVAS_FOLDER));

        new Documenter(MODULES, Documenter.Options.defaults().withOutputFolder(CANVAS_FOLDER)).writeModulesAsPlantUml();

        var file = Path.of(CANVAS_FOLDER, "components.puml");

        assertThat(file).isRegularFile();
        var diagram = Files.readString(file);
        for (var slice : new String[] {"Home", "Articleview", "Backup"}) {
            assertThat(diagram)
                    .as("arrow from %s to wikilink", slice)
                    .contains("Rel(" + NODE + slice + ", " + NODE + "Wikilink,");
        }
    }
}
